version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add your MongoDB URI here:
      # - MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/mandava
    restart: unless-stopped

  # Optional: Add MongoDB for local development
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_DATABASE=mandava
